CREATE TABLE platform_run_artifact (
    artifact_id VARCHAR(36) NOT NULL,
    run_id VARCHAR(36) NOT NULL,
    result_id VARCHAR(64) NOT NULL,
    owner_user_id BIGINT NOT NULL,
    request_id VARCHAR(128) NOT NULL,
    request_digest CHAR(64) NOT NULL,
    visibility VARCHAR(16) NOT NULL DEFAULT 'USER',
    title VARCHAR(160) NOT NULL,
    media_type VARCHAR(128) NOT NULL,
    byte_size BIGINT NOT NULL,
    sha256 CHAR(64) NOT NULL,
    blob_ref VARCHAR(128) NOT NULL,
    state VARCHAR(16) NOT NULL,
    created_at DATETIME(3) NOT NULL,
    PRIMARY KEY (artifact_id),
    UNIQUE KEY uk_platform_run_artifact_request (run_id, owner_user_id, request_id),
    KEY idx_platform_run_artifact_page (run_id, owner_user_id, created_at, artifact_id),
    CONSTRAINT chk_platform_run_artifact_visibility CHECK (visibility = 'USER'),
    CONSTRAINT chk_platform_run_artifact_state CHECK (state IN ('STAGED', 'AVAILABLE', 'UNAVAILABLE')),
    CONSTRAINT chk_platform_run_artifact_size CHECK (byte_size >= 0),
    CONSTRAINT fk_platform_run_artifact_run FOREIGN KEY (run_id) REFERENCES platform_agent_run (run_id),
    CONSTRAINT fk_platform_run_artifact_result FOREIGN KEY (result_id) REFERENCES platform_agent_result (result_id),
    CONSTRAINT fk_platform_run_artifact_user FOREIGN KEY (owner_user_id) REFERENCES platform_user (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
